name: cicd

on: push

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client/.
          push: false
          tags: ghcr.io/mattthaber/san-test:${GITHUB_SHA}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./service/.
          push: false
          tags: ghcr.io/mattthaber/san-test:${GITHUB_SHA}
