name: cicd

on: push

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: false
          tags: ghcr.io/mattthaber/san-test-client:${{ github.sha }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./service
          push: false
          tags: ghcr.io/mattthaber/san-test-service:${{ github.sha }}
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client/.
          push: true
          tags: |
            ghcr.io/mattthaber/san-test-client:${{ github.sha }}
            ghcr.io/mattthaber/san-test-client:latest
            ghcr.io/mattthaber/san-test-client:0.0.2
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./service/.
          push: true
          tags: |
            ghcr.io/mattthaber/san-test-service:${{ github.sha }}
            ghcr.io/mattthaber/san-test-service:latest
            ghcr.io/mattthaber/san-test-service:0.0.2